version: 2

sources:
    - name: staging
      database: my-rides-antonis
      schema: trips_data_all

      tables:
        - name: rides_green
        - name: rides_yellow_union
        - name: rides_fhv